### ISSUE TITLE
Multiple-second delay for loading in-site links with no visual feedback

### ISSUE THREAD

**Issue by balupton** [rauchg/blog#5]
Whenever I click one of the essay links, it takes multiple seconds for anything to happen (usually 3), there is no feedback for this, so when it first happened, it took long enough for me to think clicking was broken, and I started cmd-clicking the different links, only after a few more seconds to go back to the original tab and noticed it had finally changed article.

I saw you had a tweet for using Rico's progress bar thing, that would go a log way.

For several of my own apps, I would do a gradual fade out of opacity for the page which works just as well: https://github.com/browserstate/ajaxify/blob/f086e25d691f0a2da39427369063c4324c134d7d/ajaxify-html5.js#L112-L115

**Comment by rauchg** [comment]
@balupton i've fixed this in `next-news.now.sh`. It's a matter of adding the same code snippet for adding NProgress :)
